### ISSUE TITLE
Always indents with tab instead of indentation char(s)

### ISSUE THREAD

**Issue by Shoozza** [jhasse/coffeepp#5]
When indenting with space (e.g. 2 spaces) the closing } will be indented with tabs.
See the line after the `return 1;` is actually `\t}` and not `\space\space}`

```coffee++
int main():
  if false:
    return 1
  return 0
```
result:
```cpp
#include "main.hpp"

int main() {
  if (false) {
    return 1;
	}
  return 0;
}
```

Shouldn't the indent output be consistent?
Tested against master (c6ef571) on Windows 10 with `coffee++ main.cf++ > out.cpp`

**Comment by jhasse** [comment]
Thanks again :) Fixed in master.
